/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_Cls */

#ifndef _Included_pkg_Cls
#define _Included_pkg_Cls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_Cls
 * Method:    f
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_f__DLjava_lang_String_2
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     pkg_Cls
 * Method:    f
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pkg_Cls_f__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
